# R4 - OSPFv2 (estado de enlace), área 0. Timers reduzidos para a demonstração.
router id 1.1.1.4;
log "/var/log/bird.log" all;

protocol device { }

protocol direct {
  ipv4;
  interface "eth*";
}

protocol kernel {
  ipv4 { import none; export where source ~ [RTS_OSPF, RTS_OSPF_IA]; };
}

protocol ospf v2 {
  ipv4 { import all; export none; };
  area 0 {
    interface "eth*" {
      type ptp;
      hello 2;
      dead 8;
    };
  };
}
