# R5 - modo ESTATICO (apenas para validar a topologia)
router id 1.1.1.5;
log "/var/log/bird.log" all;

protocol device { }

protocol kernel {
  ipv4 { import none; export where source = RTS_STATIC; };
}

protocol static {
  ipv4;
  route 192.168.1.0/24 via 10.0.51.2;
  route 192.168.2.0/24 via 10.0.51.2;
  route 192.168.3.0/24 via 10.0.45.1;
  route 192.168.4.0/24 via 10.0.45.1;
}
